language: java

sudo: required
dist: trusty
group: edge

services:
  - postgresql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6

script: java -version 2>&1 | grep 'version "9"' ; if [ $? -eq 0 ]; then echo java 9 $?; mvn test -B; else echo java lt 9 $?; mvn test javadoc:javadoc -B; fi


env:
  - MAVEN_SKIP_RC=true TRAVISBUILD=true

after_success:
  - mvn -P travis,!dev -DserviceName=travis-ci jacoco:report coveralls:report


before_install:
  - echo "127.0.0.1    $HOSTNAME" | sudo tee -a /etc/hosts
  - wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip
  - unzip -qq apache-maven-3.2.5-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.2.5
  - export PATH=$M2_HOME/bin:$PATH
  - sudo -E add-apt-repository -y ppa:openjdk-r/ppa
  - sudo -E add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get -y update
  - echo install jdk 6 7 9 10
  - sudo apt-get -y install openjdk-6-jdk openjdk-7-jdk oracle-java9-installer
  - sudo ln -s /usr/lib/jvm/java-6-openjdk-amd64 /usr/lib/jvm/java-6-openjdk
  - sudo ln -s /usr/lib/jvm/java-7-openjdk-amd64 /usr/lib/jvm/java-7-openjdk
  - sudo ln -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/java-8-oracle-amd64
  - . ./.travis/install-jdk-10.sh
  - ls -al /usr/lib/jvm/
  
before_script:
  - mysql --verbose -u root -e 'create database sfm;'
  - mysql --verbose -u root -e "CREATE USER 'sfm'@'localhost';"
  - mysql --verbose -u root -e "GRANT ALL ON sfm.* TO 'sfm'@'localhost';"
  - psql -c 'create database sfm;' -U postgres
